apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfront
  labels:
    app: webfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfront
  template:
    metadata:
      labels:
        app: webfront
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 3001
        fsGroup: 2001
      containers:
        - name: webfront
          image: oussamazaoui872/angular-app:5817171
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /var/run 
              name: nginx-run
          env:
            - name: NGINX_PID_PATH
              value: "/var/run/nginx.pid"
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: webfront
spec:
  selector:
    app: webfront
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # You can specify any available port
  type: NodePort
